---
version: 0.2

env:
  secrets-manager:
    DOCKER_PAT: "docker:pat"

phases:
  pre_build:
    commands:
      - REPOSITORY_URI=542780149388.dkr.ecr.ap-southeast-1.amazonaws.com/ct-cocatrip
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Logging in to Amazon ECR...
      - |-
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
          docker login --username AWS --password-stdin \
          542780149388.dkr.ecr.ap-southeast-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Login to Docker Hub
      - docker login --username cocatrip --password $DOCKER_PAT
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Updating lambda function...
      - |-
        aws lambda update-function-code --function-name ct-cocatrip-LF \
          --region $AWS_DEFAULT_REGION \
          --image-uri $REPOSITORY_URI:$IMAGE_TAG
