---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: AWSLambdaExecutionRole
      FunctionName: cocatrip
      PackageType: Image
      Code:
        ImageUri: String

  LambdaUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: cocatrip
