---
name: Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    environment: master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/cocatrip
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=,enable=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'cocatrip'
          namespace: 'default'
          chart: 'app'
          token: '${{ github.token }}'
          values: |
            image.tag: ${{ steps.meta.outputs.tags[0] }}
          value-files: "values.yaml"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
